# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 18:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('main_image', models.ImageField(blank=True, upload_to=b'')),
                ('short_article', ckeditor.fields.RichTextField()),
                ('article', ckeditor.fields.RichTextField()),
                ('author', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Article',
            },
        ),
    ]
