# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_auto_20160325_1719'),
        ('news', '0002_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.ManyToManyField(to='tourney.City'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
