# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 11:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160325_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u044f'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=ckeditor.fields.RichTextField(verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourney.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e \u0421\u0442\u0430\u0442\u044c\u0438'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_article',
            field=ckeditor.fields.RichTextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('russian_bowl', '\u041a\u0443\u0431\u043e\u043a \u0420\u043e\u0441\u0441\u0441\u0438\u0438'), ('region_bowl', '\u0420\u0435\u0433\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0435 \u041a\u0443\u0431\u043a\u0438'), ('online_qualifying', '\u041e\u043d\u043b\u0430\u0439\u043d \u041e\u0442\u0431\u043e\u0440\u043e\u0447\u043d\u044b\u0435')], max_length=100, verbose_name='\u0422\u0438\u043f \u0421\u0442\u0430\u0442\u044c\u0438'),
        ),
    ]
