# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160329_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourney.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
