# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 20:10
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160330_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e \u0421\u0442\u0430\u0442\u044c\u0438'),
        ),
    ]
