# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 15:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='city_css',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
