# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 21:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_auto_20160325_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulations', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0420\u0435\u0433\u043b\u0430\u043c\u0435\u043d\u0442')),
                ('states', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('technical_rules', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u041f\u0440\u0430\u0432\u0438\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '\u0413\u043e\u0440\u043e\u0434', 'verbose_name_plural': 'u\u0413\u043e\u0440\u043e\u0434\u0430'},
        ),
        migrations.AlterField(
            model_name='city',
            name='css',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='CSS'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0413\u043e\u0440\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='city',
            name='short_name',
            field=models.CharField(max_length=5, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='rules',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourney.City', unique=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
