# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0004_auto_20160329_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '\u0413\u043e\u0440\u043e\u0434', 'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430'},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430', 'verbose_name_plural': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430'},
        ),
        migrations.AlterField(
            model_name='rules',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourney.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
