# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 23:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0005_auto_20160329_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0413\u043e\u0440\u043e\u0434\u0435'),
        ),
    ]
