# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 20:10
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0006_city_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'', verbose_name='\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0413\u043e\u0440\u043e\u0434\u0430'),
        ),
    ]
