# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0008_auto_20160331_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'russian_bowl', '\u041a\u0443\u0431\u043e\u043a \u0420\u043e\u0441\u0441\u0438\u0438'), (b'region_bowl', '\u0420\u0435\u0433\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0435 \u041a\u0443\u0431\u043a\u0438'), (b'online_qualifying', '\u041e\u043d\u043b\u0430\u0439\u043d \u041e\u0442\u0431\u043e\u0440\u043e\u0447\u043d\u044b\u0435')], max_length=100, null=True, verbose_name='\u0422\u0438\u043f \u0421\u0442\u0430\u0442\u044c\u0438')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('game_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0418\u0433\u0440\u044b')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourney.City', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u0422\u0443\u0440\u043d\u0438\u0440\u044b',
                'verbose_name_plural': '\u0422\u0443\u0440\u043d\u0438\u0440',
            },
        ),
    ]
