# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0009_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='city',
            name='short_name',
            field=models.CharField(max_length=5, unique=True, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourney.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
