# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 11:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourney', '0006_city_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('thumb_image', models.ImageField(blank=True, upload_to=b'', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e')),
                ('html', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='HTML')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e')),
                ('type', models.CharField(choices=[('video', '\u0412\u0438\u0434\u0435\u043e'), ('photo', '\u0424\u043e\u0442\u043e')], max_length=100, verbose_name='\u0422\u0438\u043f \u041c\u0435\u0434\u0438\u0430')),
                ('city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourney.City', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0434\u0438\u0430',
                'verbose_name_plural': '\u041c\u0435\u0434\u0438\u0430',
            },
        ),
    ]
