# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourney.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumb_image',
            field=models.ImageField(upload_to=b'', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
    ]
