# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 20:10
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20160329_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumb_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
    ]
